server:
  port: 10000
spring:
  application:
    name: front
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/