server:
  port: 10001
spring:
  application:
    name: apigateway
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: false
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "/auth"
      refresh: "/refresh"
      register: "/auth/register"
securityconfig:
  logoutsuccssurl: /
  #免登录的url地址 /front/tologin,/front/styles/**,/front/scripts/**,/front/images/**,/front/js/**
  permitall: /front/**,/auth,/auth/**,/rest/**,/staff/register,/test/**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin;
            /test/** = admin 