server:
  port: 10001
spring:
  application:
    name: apigateway
  redis:
    host: localhost
    port: 6379
    pool: 
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/systemmanager?characterEncoding=utf8&useSSL=true
    #url: jdbc:mysql://localhost:3306/midhotel?characterEncoding=utf8
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小 最小 最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取链接超时的时间
    maxWait: 60000
    #配置间隔多久才进行检测一次，检测需要关闭的空闲链接，单位是毫秒
    timeBetweenEvictionRunsMillis: 300000
    #配置一个链接在池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个链接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面SQL将无法统计，'Wall'用于防火墙
    #filters: stat,wall,log4j,logback
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
mybatis:
  type-aliases-package: com.tiger.apigateway.entity
#  config-location:  classpath:mybatis-config.xml
#  mapper-locations: com/test/demo/test/dao/*.xml
  mapper-locations: classpath:mapper/*.xml
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "/auth"
      refresh: "/refresh"
      register: "/auth/register"
securityconfig:
  logoutsuccssurl: /
  #免登录的url地址 /front/tologin,/front/styles/**,/front/scripts/**,/front/images/**,/front/js/**
  permitall: /front/**,/auth,/auth/**,/rest/**,/staff/register,/test/**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin;
            /test/** = admin
zuul:
  routes:
    front:
      service-id: front
      path: /front/** 
logging:
  path: /logs/cloudTest/apigateway
  file: /logs/cloudTest/apigateway/apigateway.log
  config: classpath:logback-spring.xml